/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Atecofin } from './atecofin';


export interface AnagraficaDatore { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codiceFiscale?: string;
    dsDenominazioneDatore?: string;
    dsVariazioneRagSociale?: string;
    flgAzArtigiana?: string;
    flgNoAaep?: string;
    matricolaInps?: string;
    numAgenziaSommin?: string;
    numeroIscrizioneAlbo?: string;
    partitaIva?: string;
    atecofin?: Atecofin;
    cnaturaGiuridica?: string;
}
