/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';


export interface Ccnl { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codCcnlMin?: string;
    dsCcnl?: string;
    dtFine?: Date;
    dtInizio?: Date;
    dtTmst?: Date;
    idNewCcnl?: number;
    settore?: string;
    ccnl?: Ccnl;
}
