/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Comunicazione } from './comunicazione';
import { Datore } from './datore';
import { Lavoratore } from './lavoratore';
import { Rapporto } from './rapporto';


export interface ComunicazioneUrgHolder { 
    comunicazione?: Comunicazione;
    flgComPerDatore?: string;
    datore?: Datore;
    rapporto?: Rapporto;
    lavoratore?: Lavoratore;
    comune?: Comune;
}
