/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';


export interface Istat2001livello5 { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codIstat2001livello5Min?: string;
    dsComIstat2001livello5?: string;
    dtFine?: Date;
    dtInizio?: Date;
    dtTmst?: Date;
    flgVldUd?: string;
    idNewIstat?: number;
}
