/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Cittadinanza } from './cittadinanza';
import { Comune } from './comune';
import { Istat2001livello5 } from './istat2001livello5';
import { LavoratoriSilpPK } from './lavoratoriSilpPK';
import { LivelloStudio } from './livelloStudio';
import { MotivoPermesso } from './motivoPermesso';
import { Provincia } from './provincia';
import { Questura } from './questura';
import { StatiEsteri } from './statiEsteri';
import { StatusStraniero } from './statusStraniero';
import { Toponimo } from './toponimo';


export interface LavoratoreSilpEspanso { 
    apiWarnings?: Array<ApiError>;
    id?: LavoratoriSilpPK;
    categoriaAssunzione?: string;
    categoriaSoggetto?: string;
    cognome?: string;
    dataFineRapporto?: Date;
    dataInizioRapporto?: Date;
    dataNascita?: Date;
    flgImportOnline?: string;
    nome?: string;
    orarioSettContrattualeMin?: number;
    orarioSettPartTimeMin?: number;
    sesso?: string;
    comuneNascita?: Comune;
    comuneResidenza?: Comune;
    comuneDomicilio?: Comune;
    istat2001livello5?: Istat2001livello5;
    provincia?: Provincia;
    statiEsteriNascita?: StatiEsteri;
    statiEsteriResidenza?: StatiEsteri;
    toponimoDomicilio?: Toponimo;
    toponimoResidenza?: Toponimo;
    idSilLavAnagrafica?: number;
    codCpiCompentenza?: string;
    descrCpiCompentenza?: string;
    descrCpiProprieta?: string;
    codCpiProprieta?: string;
    numTelDom?: string;
    numTelRes?: string;
    dsMail?: string;
    numTelCell?: string;
    codStatoCivile?: string;
    descrStatoCivile?: string;
    flagCartaSoggiorno?: string;
    dataScadPermSogg?: Date;
    dataRichPermSogg?: Date;
    motivoPermesso?: MotivoPermesso;
    descrFax?: string;
    descrWeb?: string;
    siglaProvDomicilio?: string;
    statusStraniero?: StatusStraniero;
    cittadinanza?: Cittadinanza;
    questura?: Questura;
    descrNumDocPermSogg?: string;
    numFamiliariCarico?: string;
    idLavoratoriAccorpati?: Array<string>;
    livelloStudio?: LivelloStudio;
    capDomicilio?: string;
    capResidenza?: string;
    indirizzoDomicilio?: string;
    indirizzoResidenza?: string;
    numCivicoDomicilio?: string;
    numCivicoResidenza?: string;
}
