/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Comune } from './comune';
import { Istat2001livello5 } from './istat2001livello5';
import { LavoratoriSilpPK } from './lavoratoriSilpPK';
import { Provincia } from './provincia';
import { StatiEsteri } from './statiEsteri';
import { Toponimo } from './toponimo';


export interface LavoratoreSilp { 
    apiWarnings?: Array<ApiError>;
    id?: LavoratoriSilpPK;
    categoriaAssunzione?: string;
    categoriaSoggetto?: string;
    cognome?: string;
    dataFineRapporto?: Date;
    dataInizioRapporto?: Date;
    dataNascita?: Date;
    flgImportOnline?: string;
    nome?: string;
    orarioSettContrattualeMin?: number;
    orarioSettPartTimeMin?: number;
    sesso?: string;
    comuneNascita?: Comune;
    comuneResidenza?: Comune;
    comuneDomicilio?: Comune;
    istat2001livello5?: Istat2001livello5;
    provincia?: Provincia;
    statiEsteriNascita?: StatiEsteri;
    statiEsteriResidenza?: StatiEsteri;
    toponimoDomicilio?: Toponimo;
    toponimoResidenza?: Toponimo;
}
