/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Cittadinanza } from './cittadinanza';
import { Comune } from './comune';
import { Datore } from './datore';
import { MotivoPermesso } from './motivoPermesso';
import { Questura } from './questura';
import { StatiEsteri } from './statiEsteri';
import { StatusStraniero } from './statusStraniero';


export interface LegaleRappr { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    idUserInsert?: string;
    idUserUltMod?: string;
    dtInsert?: Date;
    dtUltMod?: Date;
    dsCognome?: string;
    dsNome?: string;
    dtNascita?: Date;
    dtScadenzaPermessoSogg?: Date;
    flgResidenzaItaliana?: string;
    flgSoggiornanteItalia?: string;
    numeroDocumento?: string;
    sesso?: string;
    datore?: Datore;
    cittadinanza?: Cittadinanza;
    comune?: Comune;
    motivoPermesso?: MotivoPermesso;
    questura?: Questura;
    statiEsteri?: StatiEsteri;
    statusStraniero?: StatusStraniero;
    idSedeAssociata?: string;
    idLegaleRapprSilp?: number;
}
