/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Ccnl } from './ccnl';
import { TipoLivelloRetrib } from './tipoLivelloRetrib';


export interface LivelloRetribuzione { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codLivello?: string;
    desLivello?: string;
    divisoreOrario?: number;
    dtFine?: Date;
    dtInizio?: Date;
    lordoMensile?: number;
    mensilita?: number;
    ordinamento?: number;
    ccnl?: Ccnl;
    tipoLivelloRetrib?: TipoLivelloRetrib;
}
