/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';


export interface LivelloStudio { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codiceLivelloMin?: string;
    codiceTitoloStudio?: string;
    dsTitolo?: string;
    dtFine?: Date;
    dtInizio?: Date;
    dtTmst?: Date;
    isced97?: string;
    isced97LevelProgDest?: string;
    sinonimoTitoloStudio?: string;
    tipoDiScuola?: string;
    titoloDiStudio?: string;
}
