/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { PersonalizProvince } from './personalizProvince';


export interface Personalizzazione { 
    apiWarnings?: Array<ApiError>;
    id?: string;
    abilitaSceltaInoltroInail?: string;
    abilitaSceltaInoltroInps?: string;
    denDestinatario?: string;
    descrizione?: string;
    dirCss?: string;
    dirImages?: string;
    dirPdf?: string;
    idAaoDestinatario?: string;
    idEnte?: string;
    istanzaDb?: string;
    linkCommaxEnabled?: string;
    logEnabled?: string;
    mailServerName?: string;
    maxNumberOfLines?: string;
    maxRecoveryNumber?: string;
    tipoDestinatario?: string;
    tipoProtocollo?: string;
    urlSitoLavoro?: string;
    urlSitoPv?: string;
    userMailName?: string;
    userMailPsw?: string;
    userServerName?: string;
    personalizProvince?: PersonalizProvince;
    cutente?: string;
}
