/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Lavoratore } from './lavoratore';
import { Rapporto } from './rapporto';
import { SedeLavoro } from './sedeLavoro';


export interface RapportiLavoratoriSediInteressateVD { 
    rapportoVD?: Rapporto;
    lavoratoreVD?: Lavoratore;
    sedeLavoroVD?: SedeLavoro;
}
