/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Comune } from './comune';
import { StatiEsteri } from './statiEsteri';


export interface SedeLavoro { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codCap?: string;
    dtFine?: Date;
    dtInizio?: Date;
    dtTmst?: Date;
    email?: string;
    fax?: string;
    flgComuneSilpVariato?: string;
    flgIndirizzoSilpVariato?: string;
    flgSedeLegale?: string;
    idSedeSilp?: number;
    indirizzo?: string;
    telefono?: string;
    comune?: Comune;
    statiEsteri?: StatiEsteri;
}
