/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Comune } from './comune';
import { DatiAzienda } from './datiAzienda';
import { StatiEsteri } from './statiEsteri';
import { Toponimo } from './toponimo';


export interface Sede { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    idUserInsert?: string;
    idUserUltMod?: string;
    dtInsert?: Date;
    dtUltMod?: Date;
    cap?: string;
    codUserAggiorn?: string;
    codUserInserim?: string;
    email?: string;
    fax?: string;
    indirizzo?: string;
    telefono?: string;
    datiAzienda?: DatiAzienda;
    comune?: Comune;
    statiEsteri?: StatiEsteri;
    sedeLegale?: boolean;
    sedeOperativa?: boolean;
    numeroCivico?: string;
    toponimoSede?: Toponimo;
    idSedeSilp?: string;
    patInail?: string;
    flgValida?: string;
    motivoInvalida?: string;
    numAgenziaSomministrazione?: string;
    dinserim?: Date;
    daggiorn?: Date;
}
