/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { Comune } from './comune';
import { TipoSoggettoAbilitato } from './tipoSoggettoAbilitato';


export interface SoggettoAbilitato { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    idUserInsert?: string;
    idUserUltMod?: string;
    dtInsert?: Date;
    dtUltMod?: Date;
    cap?: string;
    cfSoggetto?: string;
    cognomeDenominazione?: string;
    email?: string;
    fax?: string;
    flgAccentramento?: string;
    indirizzo?: string;
    partitaIva?: string;
    tel?: string;
    comune?: Comune;
    tipoSoggettoAbilitato?: TipoSoggettoAbilitato;
    dataAnnullamento?: Date;
}
