/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { GradoContrattuale } from './gradoContrattuale';
import { Istat2001livello5 } from './istat2001livello5';


export interface Tutore { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    cfTutore?: string;
    cognome?: string;
    dsLivelloInquadramento?: string;
    dtNascita?: Date;
    dtVisitaMedica?: Date;
    flgAccettazione?: string;
    flgTitolare?: string;
    nome?: string;
    numAnniEsperienza?: number;
    sesso?: string;
    gradoContrattuale?: GradoContrattuale;
    istat?: Istat2001livello5;
}
