/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { DatiAzienda } from './datiAzienda';
import { Ruolo } from './ruolo';


export interface Utente { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codiceFiscale?: string;
    cognome?: string;
    nome?: string;
    email?: string;
    ruolo?: Ruolo;
    datiAzienda?: DatiAzienda;
    codiceEnteApl?: string;
}
