/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { TipoComunicazione } from './tipoComunicazione';
import { TipoSomministrazione } from './tipoSomministrazione';


export interface VariazioneSomm { 
    apiWarnings?: Array<ApiError>;
    id?: number;
    codTipoVariazioneMin?: string;
    dsVariazione?: string;
    dtFine?: Date;
    dtInizio?: Date;
    tipoComunicazione?: TipoComunicazione;
    tipoSomministrazione?: TipoSomministrazione;
}
