/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comunicazione } from './comunicazione';
import { LavoratoreSilpEspanso } from './lavoratoreSilpEspanso';
import { Ruolo } from './ruolo';


export interface WrapperLavoratoreSilpEspanso { 
    ruolo?: Ruolo;
    lavoratoreSilpEspanso?: LavoratoreSilpEspanso;
    comunicazione?: Comunicazione;
}
