/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnagraficaGenerica } from '../model/anagraficaGenerica';
import { ApiError } from '../model/apiError';
import { CommaxParametri } from '../model/commaxParametri';
import { ComonlsParametri } from '../model/comonlsParametri';
import { Ruolo } from '../model/ruolo';
import { UserAccessLog } from '../model/userAccessLog';


import { Configuration }                                     from '../configuration';


export interface CommonServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Ricerca parametro
    * 
    */
    getApplicativoAbilitato(extraHttpRequestParams?: any): Observable<ComonlsParametri>;

    /**
    * Ricerca parametro
    * 
    * @param descrizioneParametro 
    */
    getParametroByDescrizione(descrizioneParametro: string, extraHttpRequestParams?: any): Observable<ComonlsParametri>;

    /**
    * get parametro
    * 
    * @param idParametro 
    */
    getParametroCommaxById(idParametro: number, extraHttpRequestParams?: any): Observable<CommaxParametri>;

    /**
    * Restituisce la lista di ruoli legati al codice fiscale dell&#39;identita&#39; di iride registrati su sistema.
    * 
    */
    getRuoli(extraHttpRequestParams?: any): Observable<Array<Ruolo>>;

    /**
    * Inserisce dati dello utente loggato sulla tabella di log su sistema.
    * 
    * @param body 
    */
    insertUserAccessLog(body?: UserAccessLog, extraHttpRequestParams?: any): Observable<UserAccessLog>;

    /**
    * Ricerca province
    * 
    * @param cf 
    */
    preCompilaAnagraficaByCf(cf: string, extraHttpRequestParams?: any): Observable<AnagraficaGenerica>;

}
