/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DelegatoImpresa } from '../model/delegatoImpresa';
import { DelegatoImpresaSpec } from '../model/delegatoImpresaSpec';
import { SetDataAnnullamentoAllCfImpresaRes } from '../model/setDataAnnullamentoAllCfImpresaRes';


import { Configuration }                                     from '../configuration';


export interface DelegatoImpresaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Restuisce i DelegatoImpresa arricchiti di una impresa
    * 
    * @param cfImpresa 
    */
    getDelegatoImpresaSpec(cfImpresa: string, extraHttpRequestParams?: any): Observable<Array<DelegatoImpresaSpec>>;

    /**
    * Inserisce il delegato impresa
    * 
    * @param body 
    */
    postDelegatoImpresa(body?: DelegatoImpresa, extraHttpRequestParams?: any): Observable<DelegatoImpresa>;

    /**
    * Annulla o ripristina un DelegatoImpresa impostando dataAnnullamento a data di sistema
    * 
    * @param cfImpresa 
    * @param flgAutorizzazione 
    * @param flgAnnullamento 
    */
    setDataAnnullamentoAllCfImpresa(cfImpresa: string, flgAutorizzazione: boolean, flgAnnullamento: boolean, extraHttpRequestParams?: any): Observable<SetDataAnnullamentoAllCfImpresaRes>;

    /**
    * Annulla o ripristina un DelegatoImpresa impostando dataAnnullamento a data di sistema
    * 
    * @param cfDelegato 
    * @param tipoAnagrafica 
    * @param cfImpresa 
    */
    setDataAnnullamentoDelegatoImpresa(cfDelegato: string, tipoAnagrafica: string, cfImpresa: string, extraHttpRequestParams?: any): Observable<Date>;

}
