/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { DatiAzienda } from '../model/datiAzienda';
import { LavoratoreSilpEspanso } from '../model/lavoratoreSilpEspanso';
import { Sede } from '../model/sede';
import { WrapperLavoratoreSilpEspanso } from '../model/wrapperLavoratoreSilpEspanso';


import { Configuration }                                     from '../configuration';


export interface SilpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Ricerca Azienda su AAEP
    * 
    * @param codiceFiscale 
    */
    getAziendaAaep(codiceFiscale: string, extraHttpRequestParams?: any): Observable<DatiAzienda>;

    /**
    * Ricerca Azienda su Silp
    * 
    * @param codiceFiscale 
    */
    getAziendaSilp(codiceFiscale: string, extraHttpRequestParams?: any): Observable<DatiAzienda>;

    /**
    * Ricerca Lavoratore Espanso su Silp
    * 
    * @param codiceFiscale 
    * @param cognome 
    * @param nome 
    */
    getLavoratoreSilpEspanso(codiceFiscale: string, cognome?: string, nome?: string, extraHttpRequestParams?: any): Observable<LavoratoreSilpEspanso>;

    /**
    * Ricerca Sedi su Silp
    * 
    * @param idAzienda 
    */
    getSediSilp(idAzienda: string, extraHttpRequestParams?: any): Observable<Sede>;

    /**
    * Put azienza
    * 
    * @param body 
    */
    putAziendaSilp(body?: DatiAzienda, extraHttpRequestParams?: any): Observable<DatiAzienda>;

    /**
    * Put lavoratore
    * 
    * @param body 
    */
    putLavoratoreSilp(body?: LavoratoreSilpEspanso, extraHttpRequestParams?: any): Observable<LavoratoreSilpEspanso>;

    /**
    * Put lavoratore silp da co
    * 
    * @param flgRettifica 
    * @param body 
    */
    putLavoratoreSilpDaCo(flgRettifica: boolean, body?: WrapperLavoratoreSilpEspanso, extraHttpRequestParams?: any): Observable<string>;

}
