/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';


import { Configuration }                                     from '../configuration';


export interface SystemServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * 
    */
    ping1(extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Restituisce dati registrati su sistema.
    * 
    * @param code 
    */
    testError(code: number, extraHttpRequestParams?: any): Observable<ApiError>;

}
