/**
 * ComonlWeb
 * API per ComonlWeb
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/apiError';
import { Utente } from '../model/utente';


import { Configuration }                                     from '../configuration';


export interface UtenteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Restituisce l&#39;utente che effettua la chiamata.
    * 
    */
    getUtenteSelf(extraHttpRequestParams?: any): Observable<Utente>;

}
