/*-
 * ========================LICENSE_START=================================
 * COMONL BackEnd - EJB submodule
 * %%
 * Copyright (C) 2022 Regione Piemonte
 * %%
 * SPDX-FileCopyrightText: Copyright 2022 | Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2-or-later-or-later
 * =========================LICENSE_END==================================
 */
package it.csi.comonl.comonlweb.ejb.util.commax.util;

public interface ErrorConstants {
	
  // ANAGRAFICA DATORE  1000  		 
  public final static long DATORE_CODICE_FISCALE_NON_VALIDO = 10001;	
  public final static long DATORE_CODICE_ATECO_NON_VALIDO = 10002;
  public final static long DATORE_NUM_ISCRIZIONE_ALBO_NON_VALIDO = 10003;
  public final static long DATORE_SEDE_LEGALE_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10004;
  public final static long DATORE_SEDE_LEGALE_EMAIL_FORMATO_NON_CORRETTO = 10005;
  public final static long DATORE_SEDE_OPERATIVA_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10006;
  public final static long DATORE_SEDE_OPERATIVA_EMAIL_FORMATO_NON_CORRETTO = 10007;
  public final static long DATORE_PRECEDENTE_CODICE_FISCALE_NON_VALIDO = 10008;	
  public final static long DATORE_PRECEDENTE_CODICE_ATECO_NON_VALIDO = 10009;
  public final static long DATORE_PRECEDENTE_SEDE_LEGALE_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10010;
  public final static long DATORE_PRECEDENTE_SEDE_LEGALE_EMAIL_FORMATO_NON_CORRETTO = 10011;
  public final static long DATORE_PRECEDENTE_SEDE_OPERATIVA_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10012;
  public final static long DATORE_PRECEDENTE_SEDE_OPERATIVA_EMAIL_FORMATO_NON_CORRETTO = 10013;
  public final static long DATORE_DENOMINAZIONE_PRECEDENTE_DEVE_ESSERE_DIVERSA_DA_DENOMINAZIONE_ATTUALE = 10014;
  public final static long DATORE_CODICE_TRASFERIMENTO_OBBLIGATORIO_NON_VALORIZZATO = 10015;
  public final static long DATORE_CODICE_TRASFERIMENTO_NON_TROVATO = 10016;
  public static final long DATORE_SEDE_LEGALE_COMUNE_NON_VALIDO = 10017;
  public static final long DATORE_SEDE_OPERATIVA_COMUNE_O_STATO_ESTERO_NON_VALIDO = 10018;
//  public static final long DATORE_PRECEDENTE_SEDE_OPERATIVA_COMUNE_O_STATO_ESTERO_NON_VALIDO = 10019;
//  public static final long DATORE_PRECEDENTE_SEDE_LEGALE_COMUNE_O_STATO_ESTERO_NON_VALIDO = 10020;
  public static final long DATORE_SEDE_LAVORO_NON_PIEMONTESE_E_NON_ACCENTRATO = 10021;
  public static final long VARDATORI_DATORE_SEDE_LEGALE_NON_PIEMONTESE_E_NON_ACCENTRATO = 10022;
  public static final long DATORE_SEDE_OPERATIVA_NON_PIEMONTESE_E_NON_ACCENTRATO = 10023;
//  public static final long DATORE_RESIDENZA_COMUNE_O_STATO_ESTERO_NON_VALIDO = 10024;
  public static final long DATORE_RESIDENZA_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10025;
  public static final long DATORE_RESIDENZA_EMAIL_FORMATO_NON_CORRETTO = 10026;
//  public static final long DATORE_SEDE_LAVORO_COMUNE_O_STATO_ESTERO_NON_VALIDO = 10027;
  public static final long DATORE_SEDE_LAVORO_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 10028;
  public static final long DATORE_SEDE_LAVORO_EMAIL_FORMATO_NON_CORRETTO = 10029;
  public static final long DATORE_AMMESSI_DENOMINAZIONE_O_COGNOME_E_NOME = 10030;
  public static final long DATORE_INCONGRUENZA_TRA_CODICE_FISCALE_E_COGNOME_NOME = 10031;
  public static final long DATORE_PRECEDENTE_SEDE_LEGALE_COMUNE_NON_VALIDO = 10032;
  public final static long DATORE_DENOMINAZIONE_PRECEDENTE_O_DATA_VARIAZIONE_RAGIONE_SOCIALE_NON_VALORIZZATA = 10033;
  public final static long DATORE_CODICE_FISCALE_AZIENDA_PRECEDENTE_UGUALE_CODICE_FISCALE_AZIENDA_ATTUALE = 10034;
  public final static long DATORE_CODICE_FISCALE_DATORE_LAVORO_UGUALE_CODICE_FISCALE_LAVORATORE = 10035;
  public final static long DATORE_AZIENDA_NON_DI_COMPETENZA_DELL_UTENTE = 10036;
  public final static long DATORE_FLG_PUBBLICA_AMMINISTRAZIONE_NON_VALORIZZATO = 10037;
  public final static long DATORE_FLG_PUBBLICA_AMMINISTRAZIONE_ERRATO = 10038;
  public final static long DATORE_DATA_FINE_RAMO_AFFITTO_OBBLIGATORIA = 10039;
  public final static long DATORE_DATA_FINE_RAMO_AFFITTO_NON_AMMESSA = 10040;
  public final static long DATORE_DATA_FINE_RAMO_AFFITTO_INFERIORE_DATA_INIZIO = 10041;
  public final static long DATORE_SEDE_OPERATIVA_ESTERA_CON_CAP_VALORIZZATO = 10042;
  public final static long DATORE_SEDE_OPERATIVA_CON_CAP_NON_VALORIZZATO = 10043; 
  public final static long DATORE_SEDE_LEGALE_STATO_ESTERO_NON_VALIDO = 10044;
  public final static long DATORE_SEDE_LEGALE_CAP_VALORIZZATO_PER_AZI_ESTERA = 10045;
  public final static long DATORE_SEDE_LEGALE_CAP_OBBLIGATORIO = 10046;
  public final static long DATORE_LEGALE_RAPPRESENTANTE_CODICE_CITTADINANZA_NON_VALIDO = 10047;
  public final static long DATORE_LEGALE_RAPPRESENTANTE_COMUNE_O_STATO_ESTERO_NASCITA_NON_VALIDO = 10048;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_CODICE_QUESTURA_NON_AMMESSO = 10049;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_CODICE_QUESTURA_NON_VALIDO = 10050;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_CODICE_QUESTURA_NON_VALORIZZATO = 10051;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_DATA_SCADENZA_PERMESSO_DIVERSA_DA_01_01_1900 = 10052;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_DATA_SCADENZA_PERMESSO_DIVERSA_DA_31_12_2099 = 10053;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_DATA_SCADENZA_PERMESSO_PRECEDENTE_AL_01_01_2000 = 10054;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_DATI_ANAGRAFICI_NON_VALORIZZATI = 10055;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_MOTIVO_PERMESSO_NON_VALIDO = 10056;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_TIPO_DOCUMENTO_NON_VALIDO = 10057;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_TITOLO_SOGGIORNO_NON_AMMESSO = 10058;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_TITOLO_SOGGIORNO_NON_VALORIZZATO = 10059;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_SOGGIORNANTE_IN_ITALIA_NON_VALORIZZATO = 10060;
  public static final long DATORE_LEGALE_RAPPRESENTANTE_SOGGIORNANTE_IN_ITALIA_NON_AMMESSO = 10061;
  public final static long DATORE_DATA_FINE_RAMO_AFFITTO_INFERIORE_O_UGUALE_DATA_INIZIO = 10062;
  

  
    
  // AZIENDA UTILIZZATRICE
  public static final long AZIENDA_UTILIZZATRICE_CODICE_FISCALE_NON_VALIDO = 20001;
  public static final long AZIENDA_UTILIZZATRICE_CODICE_FISCALE_ERRATO_UGUALE_DATORE_LAVORO = 20002;
  public static final long AZIENDA_UTILIZZATRICE_CODICE_ATECO_NON_VALIDO = 20003;
//  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_COMUNE_O_STATO_ESTERO_NON_VALIDO = 20004;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 20005;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_EMAIL_FORMATO_NON_CORRETTO = 20006;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_COMUNE_O_STATO_ESTERO_NON_VALIDO = 20007;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_NESSUN_CAMPO_VALORIZZATO_FAX_TEL_EMAIL = 20008;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_EMAIL_FORMATO_NON_CORRETTO = 20009;
  public static final long AZIENDA_UTILIZZATRICE_FLG_PUBBLICA_AMMINISTRAZIONE_NON_VALORIZZATO = 20010;
  public static final long AZIENDA_UTILIZZATRICE_FLG_PUBBLICA_AMMINISTRAZIONE_ERRATO = 20011;
  public static final long AZIENDA_UTILIZZATRICE_CODICE_FISCALE_OBBLIGATORIO = 20012;
  public static final long AZIENDA_UTILIZZATRICE_CODICE_FISCALE_VALORIZZATO_PER_AZI_ESTERA = 20013;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_COMUNE_NON_VALIDO = 20014;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_STATO_ESTERO_NON_VALIDO = 20015;  
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_CAP_VALORIZZATO_PER_AZI_ESTERA = 20016;
  public static final long AZIENDA_UTILIZZATRICE_SEDE_LEGALE_CAP_OBBLIGATORIO = 20017;
  public static final long AZIENDA_UTILIZZATRICE_DATA_FINE_CONTRATTO_SOMMINISTRAZIONE_OBBLIGATORIA = 20018;
  public static final long AZIENDA_UTILIZZATRICE_DATA_INIZIO_CONTRATTO_SOMMINISTRAZIONE_OBBLIGATORIA = 20019;
  public final static long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_ESTERA_CON_CAP_VALORIZZATO = 20020;
  public final static long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_CON_CAP_NON_VALORIZZATO = 20021;
  public final static long AZIENDA_UTILIZZATRICE_SEDE_OPERATIVA_STATO_ESTERO_NON_AMMESSO = 20022;


  
  // LAVORATORE
  public static final long LAVORATORE_CODICE_FISCALE_NON_VALIDO = 30001;
  public static final long LAVORATORE_COGNOME_INCONGRUENTE_CON_CODICE_FISCALE = 30002;
  public static final long LAVORATORE_NOME_INCONGRUENTE_CON_CODICE_FISCALE = 30003; 
  public static final long LAVORATORE_SESSO_INCONGRUENTE_CON_CODICE_FISCALE = 30004;
  public static final long LAVORATORE_DATA_NASCITA_INCONGRUENTE_CON_CODICE_FISCALE = 30005;
  public static final long LAVORATORE_COMUNE_NASCITA_INCONGRUENTE_CON_CODICE_FISCALE = 30006;
  public static final long LAVORATORE_CODICE_CITTADINANZA_NON_VALIDO = 30007;
  public static final long LAVORATORE_CODICE_TIPO_DOCUMENTO_NON_VALIDO = 30008;
  public static final long LAVORATORE_CODICE_TIPO_DOCUMENTO_NON_VALORIZZATO = 30009;
  public static final long LAVORATORE_CODICE_MOTIVO_PERMESSO_NON_VALORIZZATO = 30010;
  public static final long LAVORATORE_CODICE_MOTIVO_PERMESSO_NON_VALIDO = 30011;
  public static final long LAVORATORE_DATA_SCADENZA_PERMESSO_NON_VALORIZZATO = 30012;
  public static final long LAVORATORE_COMUNE_DOMICILIO_NON_VALIDO = 30013;
  public static final long LAVORATORE_LIVELLO_ISTRUZIONE_STUDIO_NON_VALIDO = 30014;
  public static final long LAVORATORE_DATA_NASCITA_E_DATA_INIZIO_RAPPORTO_FUORI_RANGE = 30015;
  public static final long LAVORATORE_SUSSISTENZA_SISTEMAZIONE_ALLOGGIATIVA_E_IMPEGNO_PAGAM_RIMPATRIO_COMPILATI_PARZIALMENTE = 30016;
  public static final long LAVORATORE_FLAG_IMPEGNO_DATORE_PAGAMENTO_SPESE_RIMPATRIO_OBBLIGATORIO = 30017;
  public static final long LAVORATORE_DATA_SCADENZA_PERMESSO_PRECEDENTE_AL_01_01_2000 = 30018;
  public static final long LAVORATORE_FLAG_SUSSISTENZA_SISTEMAZIONE_ALLOGGIATIVA_NON_AMMESSO = 30019;
  public static final long LAVORATORE_FLAG_IMPEGNO_DATORE_PAGAMENTO_SPESE_RIMPATRIO_NON_AMMESSO = 30020;
  public static final long LAVORATORE_CODICE_TIPO_DOCUMENTO_NON_AMMESSO = 30021;
  public static final long LAVORATORE_CODICE_MOTIVO_PERMESSO_NON_AMMESSO = 30022;
  public static final long LAVORATORE_CODICE_QUESTURA_NON_AMMESSO = 30023;
  public static final long LAVORATORE_CODICE_QUESTURA_NON_VALIDO = 30024; 
  public static final long LAVORATORE_CODICE_QUESTURA_NON_VALORIZZATO = 30025;
  public static final long LAVORATORE_DATA_SCADENZA_PERMESSO_DIVERSA_DA_01_01_1900 = 30026;
  public static final long LAVORATORE_DATA_SCADENZA_PERMESSO_DIVERSA_DA_31_12_2099 = 30027;
  public static final long LAVORATORE_DATA_NASCITA_MAGGIORE_DATA_INIZIO_RAPPORTO = 30028;
  public static final long LAVORATORE_COMUNE_O_STATO_ESTERO_NASCITA_NON_VALIDO = 30029;
  
  
  
  

  // LAVORATORE COOBBLIGATO
  public static final long LAVORATORE_COOBBLIGATO_CODICE_FISCALE_NON_VALIDO = 40001;
  public static final long LAVORATORE_COOBBLIGATO_COGNOME_INCONGRUENTE_CON_CODICE_FISCALE = 40002;
  public static final long LAVORATORE_COOBBLIGATO_NOME_INCONGRUENTE_CON_CODICE_FISCALE = 40003; 
  public static final long LAVORATORE_COOBBLIGATO_SESSO_INCONGRUENTE_CON_CODICE_FISCALE = 40004;
  public static final long LAVORATORE_COOBBLIGATO_DATA_NASCITA_INCONGRUENTE_CON_CODICE_FISCALE = 40005;
  public static final long LAVORATORE_COOBBLIGATO_COMUNE_NASCITA_INCONGRUENTE_CON_CODICE_FISCALE = 40006;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_CITTADINANZA_NON_VALIDO = 40007;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_TIPO_DOCUMENTO_NON_VALIDO = 40008;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_TIPO_DOCUMENTO_NON_VALORIZZATO = 40009;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_MOTIVO_PERMESSO_NON_VALORIZZATO = 40010;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_MOTIVO_PERMESSO_NON_VALIDO = 40011;
  public static final long LAVORATORE_COOBBLIGATO_DATA_SCADENZA_PERMESSO_NON_VALORIZZATO = 40012;
  public static final long LAVORATORE_COOBBLIGATO_COMUNE_DOMICILIO_NON_VALIDO = 40013;
  public static final long LAVORATORE_COOBBLIGATO_LIVELLO_ISTRUZIONE_STUDIO_NON_VALIDO = 40014;
  public static final long LAVORATORE_COOBBLIGATO_DATA_NASCITA_E_DATA_INIZIO_RAPPORTO_FUORI_RANGE = 40015;
  public static final long LAVORATORE_COOBBLIGATO_SUSSISTENZA_SISTEM_ALLOGG_E_IMPEGNO_PAGAM_RIMPATRIO_COMPILATI_PARZIALMENTE = 40016;
  public static final long LAVORATORE_COOBBLIGATO_FLAG_IMPEGNO_DATORE_PAGAMENTO_SPESE_RIMPATRIO_OBBLIGATORIO = 40017;
  public static final long LAVORATORE_COOBBLIGATO_DATA_SCADENZA_PERMESSO_PRECEDENTE_AL_01_01_2000 = 40018;
  public static final long LAVORATORE_COOBBLIGATO_FLAG_SUSSISTENZA_SISTEMAZIONE_ALLOGGIATIVA_NON_AMMESSO = 40019;
  public static final long LAVORATORE_COOBBLIGATO_FLAG_IMPEGNO_DATORE_PAGAMENTO_SPESE_RIMPATRIO_NON_AMMESSO = 40020;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_TIPO_DOCUMENTO_NON_AMMESSO = 40021;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_MOTIVO_PERMESSO_NON_AMMESSO = 40022;
  public static final long LAVORATORE_COOBBLIGATO_DATA_SCADENZA_PERMESSO_DIVERSA_DA_01_01_1900 = 40023;
  public static final long LAVORATORE_COOBBLIGATO_DATA_SCADENZA_PERMESSO_DIVERSA_DA_31_12_2099  = 40024;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_QUESTURA_NON_VALIDO = 40025;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_QUESTURA_NON_AMMESSO = 40026;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_QUESTURA_NON_VALORIZZATO = 40027;
  public static final long LAVORATORE_COOBBLIGATO_DATA_NASCITA_MAGGIORE_DATA_INIZIO_RAPPORTO = 40028;
  public static final long LAVORATORE_COOBBLIGATO_CODICE_FISCALE_UGUALE_CODICE_FISCALE_DEL_LAVORATORE = 40029;
  public static final long LAVORATORE_COOBBLIGATO_COMUNE_O_STATO_ESTERO_NASCITA_NON_VALIDO = 40030;
  
  
    
  
  
  //DATI INVIO
  public final static long DATI_INVIO_CODICE_COMUNICAZIONE_PRECEDENTE_NON_VALORIZZATO= 50001;	
  public final static long DATI_INVIO_DESCRIZIONE_FORZA_MAGGIORE_NON_VALORIZZATO= 50002;
  public final static long DATI_INVIO_TIPO_COMUNICAZIONE_NON_VALIDO= 50003;
  public static final long DATI_INVIO_CODICE_COMUNICAZIONE_GIA_VALORIZZATO = 50004;
  public static final long DATI_INVIO_FLAG_ASSUNZIONE_FORZA_MAGGIORE_ERRATO = 50005;
  public final static long DATI_INVIO_CODICE_COMUNICAZIONE_PRECEDENTE_NON_PRESENTE_SU_DB= 50006;
  public final static long DATI_INVIO_CODICE_COMUNICAZIONE_PRECEDENTE_NON_VALIDO = 50007;
  public final static long DATI_INVIO_COMUNICAZIONE_FUORI_TERMINE_MASSIMO = 50008;
  public final static long DATI_INVIO_COMUNICAZIONE_RETTIFICA_SUI_DATI_ESSENZIALI_NON_AMMESSA = 50009; 
  public final static long DATI_INVIO_CODICE_COMUNICAZIONE_NON_VALIDO = 50010; 
  public final static long DATI_INVIO_CODICE_COMUNICAZIONE_NON_AMMESSO = 50011; 
  public final static long ANNULLAMENTO_OLTRE_TERMINE_PROCEDERE_CON_CESSAZIONE = 50012;
  
  // MISSIONE
  public static final long MISSIONE_INIZIO_DATA_FINE_MISSIONE_INFERIORE_DATA_INIZIO_MISSIONE = 60001;
  public static final long MISSIONE_INIZIO_DATA_FINE_MISSIONE_NON_VALORIZZATO = 60002;
  public static final long MISSIONE_INIZIO_PATINAIL_NON_VALORIZZATO = 60003;
  public static final long MISSIONE_INIZIO_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 60004;
  public static final long MISSIONE_INIZIO_FLAG_RISCHIO_SILICOSI_ASBETOSI_FORMATO_NON_VALIDO = 60005; 
  public static final long MISSIONE_INIZIO_CODICE_AGEVOLAZIONE_NON_VALIDO = 60006;
  public static final long MISSIONE_INIZIO_FLAG_SOMMINISTRAZIONE_FORMATO_NON_VALIDO = 60007;
  public static final long MISSIONE_INIZIO_TIPO_ORARIO_NON_VALIDO = 60008;
  public static final long MISSIONE_INIZIO_ORE_SETTIMANALI_MEDIE_NON_VALORIZZATE = 60009;  
  public static final long MISSIONE_INIZIO_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 60010; 
  public static final long MISSIONE_INIZIO_CCNL_NON_VALIDO = 60011;
  public static final long MISSIONE_PROROGA_DATA_FINE_PROROGA_MAGGIORE_DATA_INIZIO_RAPPORTO = 60012;
  public static final long MISSIONE_TRASFORMAZIONE_DATA_TRASFORMAZIONE_MAGGIORE_DATA_INIZIO_RAPPORTO = 60013;  
  public static final long MISSIONE_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_NON_VALIDO = 60014;
  public static final long MISSIONE_CESSAZIONE_DATA_CESSAZIONE_MAGGIORE_DATA_INIZIO_RAPPORTO = 60015;  
  public static final long MISSIONE_CESSAZIONE_CODICE_CESSAZIONE_NON_VALIDO = 60016;
  public static final long MISSIONE_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_NON_SONO_AMMESSE_TIPOLOGIE_A_TEMPO_INDETERMINATO = 60017;  
  public static final long MISSIONE_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 60018;
  public static final long MISSIONE_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 60019;
  public static final long MISSIONE_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 60020;
  public static final long MISSIONE_INIZIO_DATA_FINE_INFERIORE_ALLA_DATA_FINE_MISSIONE = 60021;
  public static final long MISSIONE_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_NON_SONO_AMMESSE_TIPOLOGIE_DI_DISTACCO = 60022;
  public static final long MISSIONE_INIZIO_ORE_SETTIMANALI_MEDIE_VALORIZZATE = 60023;
  public static final long MISSIONE_DIFFERENZA_DATA_FINE_DATA_INIZIO_SUPERIORE_A_50_ANNI = 60024;
  public static final long MISSIONE_DATA_INIZIO_MISSIONE_INFERIORE_ALLA_DATA_INIZIO_CONTRATTO_SOMMINISTRAZIONE = 60025;
  public static final long MISSIONE_DATA_FINE_CONTRATTO_SOMMINISTRAZIONE_INFERIORE_ALLA_DATA_FINE_MISSIONE = 60026;
  public static final long MISSIONE_DATA_INIZIO_MISSIONE_INFERIORE_ALLA_DATA_INIZIO_RAPPORTO = 60027;
  public static final long MISSIONE_CESSAZIONE_CODICE_CAUSA_NON_AMMESSA = 60028;
  public static final long MISSIONE_TRASFORMAZIONE_TIPOLOGIA_DI_TRASFORMAZIONE_NON_AMMESSA = 60029;
  public static final long  MISSIONE_PROROGA_DATA_FINE_PROROGA_MISSIONE_MAGGIORE_DATA_FINE_PROROGA = 60030;
  public static final long  MISSIONE_PROROGA_DATA_FINE_CONTRATTO_SOMMINISTRAZIONE_MAGGIORE_DATA_FINE_PROROGA = 60031;
  public static final long MISSIONE_INIZIO_CODICE_AGEVOLAZIONE_DUPLICATO = 60049;
  //adeguamenti 2016
  public static final long MISSIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 60050;
  public static final long MISSIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 60051;
  public static final long MISSIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 60052;
  public static final long MISSIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 60053;
  //adeguamenti 2019
  public static final long MISSIONE_RETRIBUZIONE_NON_VALORIZZATA = 60054;
  public static final long MISSIONE_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 60055;
  public static final long MISSIONE_LIVELLO_INQUADRAMENTO_NON_VALIDO_PER_CCNL = 60056;
  public static final long MISSIONE_IMPOSSIBILE_CALCOLARE_RETRIBUZIONE_MANCANZA_CAMPI_OBBLIGATORI = 60057;
  public static final long MISSIONE_RETRIBUZIONE_INSERITA_NON_VALIDA = 60058;
  public static final long MISSIONE_AGEVOLAZIONI_NON_AMMESSE = 60059;
  public static final long MISSIONE_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 60060;
  
  //VARIAZIONE
  public static final long VARIAZIONE_PROROGA_DATA_INIZIO_RAPPORTO_MAGGIORE_DATA_FINE_PROROGA = 60032;
  public static final long VARIAZIONE_PROROGA_DATA_INIZIO_MISSIONE_MAGGIORE_DATA_FINE_PROROGA = 60033;  
  public static final long VARIAZIONE_PROROGA_DATA_FINE_MISSIONE_MAGGIORE_DATA_FINE_PROROGA = 60034;
  public static final long VARIAZIONE_PROROGA_DATA_FINE_PROROGA_MAGGIORE_DATA_FINE_RAPPORTO = 60035;
  public static final long VARIAZIONE_PROROGA_DIFFERENZA_DATA_FINE_PROROGA_DATA_INIZIO_RAPPORTO_SUPERIORE_A_50_ANNI = 60036;
  
  
  public static final long VARIAZIONE_TRAFORMAZIONE_DATA_INIZIO_RAPPORTO_MAGGIORE_DATA_TRASFORMAZIONE = 60037;
  public static final long VARIAZIONE_TRAFORMAZIONE_DATA_INIZIO_MISSIONE_MAGGIORE_DATA_TRASFORMAZIONE = 60038; 
  public static final long VARIAZIONE_TRAFORMAZIONE_DATA_TRASFORMAZIONE_MAGGIORE_DATA_FINE_RAPPORTO = 60039;
  public static final long VARIAZIONE_TRAFORMAZIONE_DATA_TRASFORMAZIONE_MAGGIORE_DATA_FINE_SOMMINISTRAZIONE = 60040; 
  public static final long VARIAZIONE_TRASFORMAZIONE_TIPOLOGIA_DI_TRASFORMAZIONE_NON_AMMESSA = 60041;
  public static final long VARIAZIONE_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_NON_SONO_AMMESSE_TIPOLOGIE_DI_DISTACCO = 60042;
  
  
  public static final long VARIAZIONE_CESSAZIONE_DATA_INIZIO_MISSIONE_MAGGIORE_DATA_CESSAZIONE = 60043; 
  public static final long VARIAZIONE_CESSAZIONE_DATA_INIZIO_RAPPORTO_MAGGIORE_DATA_CESSAZIONE = 60044;
  public static final long VARIAZIONE_CESSAZIONE_DATA_CESSAZIONE_MAGGIORE_DATA_FINE_SOMMINISTRAZIONE = 60045; 
  public static final long VARIAZIONE_CESSAZIONE_CODICE_CAUSA_NON_AMMESSA = 60046;
  public static final long VARIAZIONE_CESSAZIONE_DIFFERENZA_DATA_CESSAZIONE_DATA_INIZIO_RAPPORTO_SUPERIORE_A_50_ANNI = 60047;
  public static final long VARIAZIONE_CESSAZIONE_CODICE_CAUSA_NON_VALIDO = 60048;
    
  
  
  
  //DATI ASSUNZIONE 
  public static final long DATI_ASSUNZIONE_DATA_FINE_MINORE_O_UGUALE_A_DATA_INIZIO_RAPPORTO = 70001; 
  public static final long DATI_ASSUNZIONE_ENTE_PREVIDENZIALE_ERRATO = 70002; 
  public static final long DATI_ASSUNZIONE_NESSUN_ENTE_PREV_MA_COD_ENTE_PREVIDENZIALE_VALORIZZATO = 70003; 
  public static final long DATI_ASSUNZIONE_PAT_INAIL_NON_VALORIZZATO = 70004; 
  public static final long DATI_ASSUNZIONE_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 70005;
  public static final long DATI_ASSUNZIONE_COD_AGEVOLAZIONE_ERRATO = 70006; 
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_ERRATO = 70007; 
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM = 70008;
  public static final long DATI_ASSUNZIONE_FORMA_INDETERMINATA_NON_AMMESSA_PER_UNISOM = 70009;
  public static final long DATI_ASSUNZIONE_LAVORATORE_COOBBLIGATO_NON_VALORIZZATO_PER_TIPO_CONTRATTO_RIPARTITO = 70010;
  public static final long DATI_ASSUNZIONE_FLG_SOCIO_LAVORATORE_ERRATO_UNILAV = 70011;
  public static final long DATI_ASSUNZIONE_TIPO_ORARIO_ERRATO_UNILAV = 70012;
  public static final long DATI_ASSUNZIONE_ORE_SETTIMANALI_MEDIE_NON_VALORIZZATE = 70013;
  public static final long DATI_ASSUNZIONE_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 70014;
  public static final long DATI_ASSUNZIONE_CCNL_NON_VALIDO = 70015;
  public static final long DATI_ASSUNZIONE_CCNL_RETRIBUZIONE_E_LIVELLO_NON_VALORIZZATI = 70016;
  public static final long DATI_ASSUNZIONE_NUM_GG_PREVISTI_AGR_NON_VALORIZZATO = 70017;
  public static final long DATI_ASSUNZIONE_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 70018;
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_RIPARTITO_NON_ANCORA_GESTITO = 70019;
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_APPRENDISTATO_NON_AMMESSO = 70020;
  public static final long DATI_ASSUNZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA = 70021;
  public static final long DATI_ASSUNZIONE_ORE_SETTIMANALI_MEDIE_VALORIZZATE = 70022;
  public static final long DATI_ASSUNZIONE_PAT_INAIL_ERRATO = 70023; 
  public static final long DATI_ASSUNZIONE_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 70024;
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNIDOM = 70025;
  public static final long DATI_ASSUNZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNILAV = 70026;
  public static final long DATI_ASSUNZIONE_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 70027;
  public static final long DATI_ASSUNZIONE_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 70028;
  public final static long DATI_ASSUNZIONE_TEMPO_INDETERMINATO_CON_DATA_FINE_VALORIZZATA = 70029;
  public final static long DATI_ASSUNZIONE_DIFFERENZA_DATA_FINE_DATA_INIZIO_SUPERIORE_A_50_ANNI = 70030;
  public final static long DATI_ASSUNZIONE_DATORE_LAVORO_CON_SEDE_LEGALE_IN_PIEMONTE_UTILIZZARE_PROCEDURA_ONLINE = 70031;
  public final static long DATI_ASSUNZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 70032;
  public final static long DATI_ASSUNZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_AMMESSO = 70033;
  public final static long DATI_ASSUNZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALIDO = 70034;
  public final static long DATI_ASSUNZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_VALORIZZATO = 70035;
  public final static long DATI_ASSUNZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_AMMESSO = 70036;
  public final static long DATI_ASSUNZIONE_DATA_FINE_PERIODO_FORMATIVO_DIVERSA_DA_DATA_FINE_RAPPORTO = 70037;
  public static final long DATI_ASSUNZIONE_DATA_INIZIO_RAPPORTO_SUCCESSIVA_ALLA_DATA_FINE_PERIODO_FORMATIVO = 70038;
  public final static long DATI_ASSUNZIONE_TEMPO_INDETERMINATO_CON_LAVORO_STAGIONALE = 70039;
  public static final long DATI_ASSUNZIONE_COD_AGEVOLAZIONE_DUPLICATO = 70040; 
  //72160-Adeguamenti 2014
  public static final long DATI_ASSUNZIONE_CCNL_NON_VALORIZZATO = 70041;
  public static final long DATI_ASSUNZIONE_RETRIBUZIONE_NON_VALORIZZATA = 70042;
  //
  public static final long DATI_ASSUNZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 70043;
  public static final long DATI_ASSUNZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 70044;
  public static final long DATI_ASSUNZIONE_CATEGORIA_TIROCINANTE_NON_VALORIZZATO = 70045;
  public static final long DATI_ASSUNZIONE_TIPOLOGIA_TIROCINIO_NON_VALORIZZATO = 70046;
  //
  public static final long DATI_ASSUNZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 70047;
  public static final long DATI_ASSUNZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 70048;
  public static final long DATI_ASSUNZIONE_CATEGORIA_TIROCINANTE_NON_AMMESSA = 70049;
  public static final long DATI_ASSUNZIONE_TIPOLOGIA_TIROCINIO_NON_AMMESSA = 70050;
  public static final long DATI_ASSUNZIONE_TIPOLOGIA_TIROCINIO_CATEGORIA_TIROCINANTE_ACCOPPIAMENTO_NON_VALIDO = 70051;
  public static final long DATI_ASSUNZIONE_FLAG_LAVORO_STAGIONALE_ERRATO = 70052;
  public static final long DATI_ASSUNZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA_CON_FLAG_LAVORO_STAGIONALE_SI = 70053;
  //
  public static final long DATI_ASSUNZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_6_MESI = 70054;
  public static final long DATI_ASSUNZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_12_MESI = 70055;
  public static final long DATI_ASSUNZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_24_MESI = 70056;
 // 
  public static final long DATI_ASSUNZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_UGUALE_CODICE_FISCALE_DATORE = 70057;
//
  public static final long DATI_ASSUNZIONE_CODICE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALIDO = 70058;
  public static final long DATI_ASSUNZIONE_CODICE_CATEGORIA_TIROCINANTE_NON_VALIDO = 70059;
  public static final long DATI_ASSUNZIONE_CODICE_TIPOLOGIA_TIROCINIO_NON_VALIDO = 70060;
  public static final long DATI_ASSUNZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_3_MESI = 70061;
  public static final long DATI_ASSUNZIONE_DURATA_RAPPORTO_TIROCINIO_NON_CONSENTITA = 70062;//71862 - COMONL-1529
  public static final long DATI_ASSUNZIONE_LAVORATORE_COOBBLIGATO_SU_TIPO_CONTRATTO_NON_AMMESSO = 70063;//72160-1549
  
  public static final long DATI_ASSUNZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 70064;
  public static final long DATI_ASSUNZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 70065;
  public static final long DATI_ASSUNZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 70066;
  public static final long DATI_ASSUNZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 70067;
  public static final long DATI_ASSUNZIONE_AGEVOLAZIONI_NON_AMMESSE = 70068;
  public static final long DATI_ASSUNZIONE_LIVELLO_INQUADRAMENTO_NON_VALIDO_PER_CCNL = 70069;
  public static final long DATI_ASSUNZIONE_IMPOSSIBILE_CALCOLARE_RETRIBUZIONE_MANCANZA_CAMPI_OBBLIGATORI = 70070;
  public static final long DATI_ASSUNZIONE_RETRIBUZIONE_INSERITA_NON_VALIDA = 70071;
  public static final long DATI_ASSUNZIONE_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 70072;
  
  //DATI CESSAZIONE
  public static final long DATI_CESSAZIONE_DATA_FINE_MINORE_O_UGUALE_A_DATA_INIZIO_RAPPORTO = 80001;
  public static final long DATI_CESSAZIONE_DATA_FINE_NON_VALORIZZATA_PER_UNISOM = 80002;
  public static final long DATI_CESSAZIONE_DATA_CESSAZIONE_MINORE_DI_DATA_INIZIO_RAPPORTO = 80003;
  public static final long DATI_CESSAZIONE_CODICE_CAUSA_NON_VALIDO = 80004;
  public static final long DATI_CESSAZIONE_ENTE_PREVIDENZIALE_ERRATO = 80005;
  public static final long DATI_CESSAZIONE_NESSUN_ENTE_PREV_MA_COD_ENTE_PREVIDENZIALE_VALORIZZATO = 80006;
  public static final long DATI_CESSAZIONE_PAT_INAIL_NON_VALORIZZATO = 80007;
  public static final long DATI_CESSAZIONE_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 80008;
  public static final long DATI_CESSAZIONE_COD_AGEVOLAZIONE_ERRATO = 80009;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_CESSAZIONE = 80010;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM = 80011;
  public static final long DATI_CESSAZIONE_LAVORATORE_COOBBLIGATO_NON_VALORIZZATO_PER_TIPO_CONTRATTO_RIPARTITO = 80012;
  public static final long DATI_CESSAZIONE_FLG_SOCIO_LAVORATORE_ERRATO_UNILAV = 80013;
  public static final long DATI_CESSAZIONE_TIPO_ORARIO_ERRATO_UNILAV = 80014;
  public static final long DATI_CESSAZIONE_NUM_ORE_SETTIMANALI_NON_VALORIZZATE = 80015;  
  public static final long DATI_CESSAZIONE_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 80016;  
  public static final long DATI_CESSAZIONE_CCNL_NON_VALIDO = 80017;
  public static final long DATI_CESSAZIONE_CCNL_RETRIBUZIONE_E_LIVELLO_NON_VALORIZZATI = 80018;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_ERRATO = 80019;
  public static final long DATI_CESSAZIONE_FORMA_INDETERMINATA_NON_AMMESSA_PER_UNISOM = 80020;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_RIPARTITO_NON_ANCORA_GESTITO = 80021;
  public static final long DATI_CESSAZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA = 80022;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_APPRENDISTATO_NON_AMMESSO = 80023;
  public static final long DATI_CESSAZIONE_CODICE_CAUSA_NON_AMMESSA = 80024;
  public static final long DATI_CESSAZIONE_CODICE_ENTE_PREVIDENZIALE_NON_VALORIZZATO = 80025;
  public static final long DATI_CESSAZIONE_PAT_INAIL_ERRATO = 80026; 
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNILAV = 80027;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNIDOM = 80028;
  public static final long DATI_CESSAZIONE_FLG_CCNL_ERRATO_UNIDOM = 80029;
  public static final long DATI_CESSAZIONE_FLG_INVALIDITA_E_O_FLG_CONVIVENZA_NON_VALORIZZATI = 80030;
  public static final long DATI_CESSAZIONE_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 80031;
  public static final long DATI_CESSAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM_DATA_INIZIO_MAGGIORE_01_01_2008 = 80032;
  public static final long DATI_CESSAZIONE_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 80033;
  public static final long DATI_CESSAZIONE_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 80034;
  public static final long DATI_CESSAZIONE_NUM_ORE_SETTIMANALI_VALORIZZATE = 80035;
  public static final long DATI_CESSAZIONE_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 80036;
  public final static long DATI_CESSAZIONE_TEMPO_INDETERMINATO_CON_DATA_FINE_VALORIZZATA = 80037;
  public final static long DATI_CESSAZIONE_DIFFERENZA_DATA_FINE_DATA_INIZIO_SUPERIORE_A_50_ANNI = 80038;
  public final static long DATI_CESSAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 80039;
  public final static long DATI_CESSAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_AMMESSO = 80040;
  public final static long DATI_CESSAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALIDO = 80041;
  public final static long DATI_CESSAZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_VALORIZZATO = 80042;
  public final static long DATI_CESSAZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_AMMESSO = 80043;
  public final static long DATI_CESSAZIONE_DATA_FINE_PERIODO_FORMATIVO_DIVERSA_DA_DATA_FINE_RAPPORTO = 80044;
  public static final long DATI_CESSAZIONE_DATA_INIZIO_RAPPORTO_SUCCESSIVA_ALLA_DATA_FINE_PERIODO_FORMATIVO = 80045;
  public static final long DATI_CESSAZIONE_TEMPO_INDETERMINATO_CON_LAVORO_STAGIONALE = 80046;
  public static final long DATI_CESSAZIONE_COD_AGEVOLAZIONE_DUPLICATO = 80047;
  //72160-Adeguamenti 2104
  public static final long DATI_CESSAZIONE_CCNL_NON_VALORIZZATO = 80048;
  public static final long DATI_CESSAZIONE_RETRIBUZIONE_NON_VALORIZZATA = 80049;
  //
  public static final long DATI_CESSAZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 80050;
  public static final long DATI_CESSAZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 80051;
  public static final long DATI_CESSAZIONE_CATEGORIA_TIROCINANTE_NON_VALORIZZATO = 80052;
  public static final long DATI_CESSAZIONE_TIPOLOGIA_TIROCINIO_NON_VALORIZZATO = 80053;
  //
  public static final long DATI_CESSAZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 80054;
  public static final long DATI_CESSAZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 80055;
  public static final long DATI_CESSAZIONE_CATEGORIA_TIROCINANTE_NON_AMMESSA = 80056;
  public static final long DATI_CESSAZIONE_TIPOLOGIA_TIROCINIO_NON_AMMESSA = 80057;
  public static final long DATI_CESSAZIONE_TIPOLOGIA_TIROCINIO_CATEGORIA_TIROCINANTE_ACCOPPIAMENTO_NON_VALIDO = 80058;
  public static final long DATI_CESSAZIONE_FLAG_LAVORO_STAGIONALE_ERRATO = 80059;
  public static final long DATI_CESSAZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA_CON_FLAG_LAVORO_STAGIONALE_SI = 80060;
 //
  public static final long DATI_CESSAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_6_MESI = 80061;
  public static final long DATI_CESSAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_12_MESI = 80062;
  public static final long DATI_CESSAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_24_MESI = 80063;
  //
  public static final long DATI_CESSAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_UGUALE_CODICE_FISCALE_DATORE = 80064;
  //
  public static final long DATI_CESSAZIONE_CODICE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALIDO = 80065;
  public static final long DATI_CESSAZIONE_CODICE_CATEGORIA_TIROCINANTE_NON_VALIDO = 80066;
  public static final long DATI_CESSAZIONE_CODICE_TIPOLOGIA_TIROCINIO_NON_VALIDO = 80067;
  public static final long DATI_CESSAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_3_MESI = 80068;
  public static final long DATI_CESSAZIONE_DURATA_RAPPORTO_TIROCINIO_NON_CONSENTITA = 80069;//71862 - COMONL-1529
  public static final long DATI_CESSAZIONE_DATA_INIZIO_RAPPORTO_MAGGIORE_DELLA_DATA_RIFERIMENTO_RAPPORTO_NON_CONSENTITA = 80074; //COMONL-1607
  //adeguamenti 2019
  public static final long DATI_CESSAZIONE_AGEVOLAZIONI_NON_AMMESSE = 80075; 
  public static final long DATI_CESSAZIONE_LIVELLO_INQUADRAMENTO_NON_VALIDO_PER_CCNL = 80076; 
  public static final long DATI_CESSAZIONE_IMPOSSIBILE_CALCOLARE_RETRIBUZIONE_MANCANZA_CAMPI_OBBLIGATORI = 80077; 
  public static final long DATI_CESSAZIONE_RETRIBUZIONE_INSERITA_NON_VALIDA = 80078; 
  public static final long DATI_CESSAZIONE_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 80079; 

  
  // RAPPORTO LAVORO -- VARDATORI  
  // ***************   NB: ATTENZIONE tutti i messaggi sono parametrici  **********************************
  public static final long RAPPLAV_VARDATORI_DATA_FINE_RAPPORTO_MAGGIORE_DATA_INIZIO_RAPPORTO = 90001;
  public static final long RAPPLAV_VARDATORI_ENTE_PREVIDENZIALE_NON_VALIDO = 90002;
  public static final long RAPPLAV_VARDATORI_NESSUN_ENTE_PREV_MA_COD_ENTE_PREVIDENZIALE_VALORIZZATO = 90003;
  public static final long RAPPLAV_VARDATORI_PAT_INAIL_NON_VALORIZZATO = 90004;
  public static final long RAPPLAV_VARDATORI_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 90005;
  public static final long RAPPLAV_VARDATORI_COD_AGEVOLAZIONE_NON_VALIDO = 90006;
  public static final long RAPPLAV_VARDATORI_TIPO_CONTRATTO_ERRATO = 90007;
  public static final long RAPPLAV_VARDATORI_TIPO_FLAG_SOCIO_LAVORATORE_NON_VALIDO = 90008;
  public static final long RAPPLAV_VARDATORI_TIPO_ORARIO_NON_VALIDO = 90009;
  public static final long RAPPLAV_VARDATORI_ORE_SETTIMANALI_MEDIE_NON_VALORIZZATE = 90010;
  public static final long RAPPLAV_VARDATORI_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 90011;
  public static final long RAPPLAV_VARDATORI_CCNL_NON_VALIDO = 90012;
  public static final long RAPPLAV_VARDATORI_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 90013;
  public static final long RAPPLAV_VARDATORI_TRASFERIMENTO_RAMO_AZIENDALE_NON_ANCORA_GESTITO = 90014;
  public static final long RAPPLAV_VARDATORI_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 90015;
  public static final long RAPPLAV_VARDATOR_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 90016;
  public static final long RAPPLAV_VARDATOR_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 90017;
  public static final long RAPPLAV_VARDATORI_ORE_SETTIMANALI_MEDIE_VALORIZZATE = 90018;
  public final static long RAPPLAV_VARDATORI_TEMPO_INDETERMINATO_CON_DATA_FINE_VALORIZZATA = 90019;
  public static final long RAPPLAV_VARDATORI_CCNL_RETRIBUZIONE_E_LIVELLO_NON_VALORIZZATI = 90020;
  public final static long RAPPLAV_VARDATORI_TEMPO_DETERMINATO_CON_DATA_FINE_NON_VALORIZZATA = 90021;
  //VARDATORI SEDE OPERATIVA
  public static final long SEDE_OPERATIVA_ESTERA_VARDATORI_CON_CAP_VALORIZZATO = 90022;
  public static final long SEDE_OPERATIVA_VARDATORI_CON_CAP_NON_VALORIZZATO = 90023;
  public static final long SEDE_OPERATIVA_VARDATORI_COMUNE_O_STATO_ESTERO_NON_VALIDO = 90024;
  //
  public final static long RAPPLAV_VARDATORI_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 90025;
  public final static long RAPPLAV_VARDATORI_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_AMMESSO = 90026;
  public final static long RAPPLAV_VARDATORI_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALIDO = 90027;
  public final static long RAPPLAV_VARDATORI_DATA_FINE_PERIODO_FORMATIVO_NON_VALORIZZATO = 90028;
  public final static long RAPPLAV_VARDATORI_DATA_FINE_PERIODO_FORMATIVO_NON_AMMESSO = 90029;
  public final static long RAPPLAV_VARDATORI_DATA_FINE_PERIODO_FORMATIVO_DIVERSA_DA_DATA_FINE_RAPPORTO = 90030;
  public static final long RAPPLAV_VARDATORI_DATA_INIZIO_RAPPORTO_SUCCESSIVA_ALLA_DATA_FINE_PERIODO_FORMATIVO = 90031;
  public final static long RAPPLAV_VARDATORI_TEMPO_INDETERMINATO_CON_LAVORO_STAGIONALE = 90032;
  public static final long RAPPLAV_VARDATORI_COD_AGEVOLAZIONE_DUPLICATO = 90033;
  public static final long RAPPLAV_VARDATORI_DATA_FINE_PERIODO_FORMATIVO_INFERIORE_O_UGUALE_DATA_INIZIO = 90034;
  //72160- Adeguamenti 2014
  public static final long RAPPLAV_VARDATORI_CCNL_NON_VALORIZZATO = 90035;
  public static final long RAPPLAV_VARDATORI_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 90036;
  public static final long RAPPLAV_VARDATORI_RETRIBUZIONE_NON_VALORIZZATA = 90037;
  public static final long RAPPLAV_VARDATORI_FLAG_LAVORO_STAGIONALE_ERRATO = 90038;
  public static final long RAPPLAV_VARDATORI_DATA_FINE_RAPPORTO_NON_VALORIZZATA_CON_FLAG_LAVORO_STAGIONALE_SI = 90039;
  //
  public static final long RAPPLAV_VARDATORI_CODICE_FISCALE_SOGGETTO_PROMOTORE_UGUALE_CODICE_FISCALE_DATORE = 90040;
  //adeguamenti 2016
  public static final long RAPPLAV_VARDATORI_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 90041;
  public static final long RAPPLAV_VARDATORI_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 90042;
  public static final long RAPPLAV_VARDATORI_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 90043;
  public static final long RAPPLAV_VARDATORI_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 90044;
  //Adeguamenti 2019
  public static final long RAPPLAV_VARDATORI_AGEVOLAZIONI_NON_AMMESSE = 90045;
  public static final long RAPPLAV_VARDATORI_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 90046;
  
  //DATI PROROGA
  public static final long DATI_PROROGA_CODICE_CAUSA_NON_VALIDO = 11001;
  public static final long DATI_PROROGA_PAT_INAIL_NON_VALORIZZATO = 11002;
  public static final long DATI_PROROGA_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 11003;
  public static final long DATI_PROROGA_COD_AGEVOLAZIONE_ERRATO = 11004;
  public static final long DATI_PROROGA_LAVORATORE_COOBBLIGATO_NON_VALORIZZATO_PER_TIPO_CONTRATTO_RIPARTITO = 11005;
  public static final long DATI_PROROGA_FLG_SOCIO_LAVORATORE_ERRATO_UNILAV = 11006;
  public static final long DATI_PROROGA_TIPO_ORARIO_ERRATO_UNILAV = 11007;
  public static final long DATI_PROROGA_ORE_SETTIMANALI_MEDIE_NON_VALORIZZATE = 11008;
  public static final long DATI_PROROGA_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 11009;
  public static final long DATI_PROROGA_CCNL_NON_VALIDO = 11010;
  public static final long DATI_PROROGA_CCNL_RETRIBUZIONE_E_LIVELLO_NON_VALORIZZATI = 11011;
  public static final long DATI_PROROGA_DATA_FINE_PROROGA_MINORE_DI_DATA_INIZIO_RAPPORTO = 11012;  
  public static final long DATI_PROROGA_FORMA_INDETERMINATA_NON_AMMESSA_PER_UNISOM = 11013;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM = 11014;
  public static final long DATI_PROROGA_NUM_GG_PREVISTI_AGR_NON_VALORIZZATO = 11015;
  public static final long DATI_PROROGA_DATA_CESSAZIONE_MINORE_DI_DATA_INIZIO_RAPPORTO = 11016;
  public static final long DATI_PROROGA_ENTE_PREVIDENZIALE_ERRATO = 11017;
  public static final long DATI_PROROGA_NESSUN_ENTE_PREV_MA_COD_ENTE_PREVIDENZIALE_VALORIZZATO = 11018;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_ERRATO = 11019;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_NON_AMMESSO_PER_PROROGA = 11020;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_APPRENDISTATO_NON_AMMESSO = 11021;
  public static final long DATI_PROROGA_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 11022;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_RIPARTITO_NON_ANCORA_GESTITO = 11023;
  public static final long DATI_PROROGA_TIPO_COMUNICAZIONE_DI_PROROGA_NON_AMMESSA = 11024;
  public static final long DATI_PROROGA_DATA_FINE_RAPPORTO_NON_VALORIZZATA = 11025;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNILAV = 11026;
  public static final long DATI_PROROGA_FORMA_INDETERMINATA_NON_AMMESSA_PER_UNIDOM = 11027;
  public static final long DATI_PROROGA_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 11028;
  public static final long DATI_PROROGA_PAT_INAIL_ERRATO = 11029; 
  public static final long DATI_PROROGA_CODICE_ENTE_PREVIDENZIALE_NON_VALORIZZATO = 11030;
  public static final long DATI_PROROGA_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM_DATA_INIZIO_MAGGIORE_01_01_2008 = 11031;
  public static final long DATI_PROROGA_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 11032;
  public static final long DATI_PROROGA_ORE_SETTIMANALI_MEDIE_VALORIZZATE = 11033;
  public static final long DATI_PROROGA_TEMPO_INDETERMINATO_CON_DATA_FINE_VALORIZZATA = 11034;
  public static final long DATI_PROROGA_DIFFERENZA_DATA_FINE_DATA_INIZIO_SUPERIORE_A_50_ANNI = 11035;
  //public static final long DATI_PROROGA_DATA_FINE_PROROGA_NON_VALORIZZATA = 11036;
  public static final long DATI_PROROGA_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 11036;
  public static final long DATI_PROROGA_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_AMMESSO = 11037;
  public static final long  DATI_PROROGA_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALIDO = 11038;
  public static final long  DATI_PROROGA_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 11039;
  public static final long DATI_PROROGA_DATA_FINE_PERIODO_FORMATIVO_NON_AMMESSO = 11040;
  public static final long DATI_PROROGA_TEMPO_INDETERMINATO_CON_LAVORO_STAGIONALE = 11041;
  public static final long DATI_PROROGA_PROSECUZIONE_DI_FATTO_NON_AMMESSA_CON_CONTRATTO_TEMPO_INDETERMINATO = 11042;  
  public static final long DATI_PROROGA_COD_AGEVOLAZIONE_DUPLICATO = 11043;
  //72160-Adeguamenti 2014
  public static final long DATI_PROROGA_CCNL_NON_VALORIZZATO = 11044;
  public static final long DATI_PROROGA_RETRIBUZIONE_NON_VALORIZZATA = 11045;
  //
  public static final long DATI_PROROGA_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 11046;
  public static final long DATI_PROROGA_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 11047;
  public static final long DATI_PROROGA_CATEGORIA_TIROCINANTE_NON_VALORIZZATO = 11048;
  public static final long DATI_PROROGA_TIPOLOGIA_TIROCINIO_NON_VALORIZZATO = 11049;
  //
  public static final long DATI_PROROGA_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 11050;
  public static final long DATI_PROROGA_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 11051;
  public static final long DATI_PROROGA_CATEGORIA_TIROCINANTE_NON_AMMESSA = 11052;
  public static final long DATI_PROROGA_TIPOLOGIA_TIROCINIO_NON_AMMESSA = 11053;
  public static final long DATI_PROROGA_TIPOLOGIA_TIROCINIO_CATEGORIA_TIROCINANTE_ACCOPPIAMENTO_NON_VALIDO = 11054;
//
public static final long DATI_PROROGA_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_6_MESI = 11055;
public static final long DATI_PROROGA_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_12_MESI = 11056;
public static final long DATI_PROROGA_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_24_MESI = 11057;
//
public static final long DATI_PROROGA_CODICE_FISCALE_SOGGETTO_PROMOTORE_UGUALE_CODICE_FISCALE_DATORE = 11058;
//
public static final long DATI_PROROGA_CODICE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALIDO = 11059;
public static final long DATI_PROROGA_CODICE_CATEGORIA_TIROCINANTE_NON_VALIDO = 11060;
public static final long DATI_PROROGA_CODICE_TIPOLOGIA_TIROCINIO_NON_VALIDO = 11061;
public static final long DATI_PROROGA_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_3_MESI = 11062;
public static final long DATI_PROROGA_DURATA_RAPPORTO_TIROCINIO_NON_CONSENTITA = 11063;//71862 - COMONL-1529



  //DATI TRASFORMAZIONE
  public static final long DATI_TRASFORMAZIONE_DATA_TRASFORMAZIONE_MINORE_DI_DATA_INIZIO_RAPPORTO = 12001;
  public static final long DATI_TRASFORMAZIONE_ENTE_PREVIDENZIALE_ERRATO = 12002;
  public static final long DATI_TRASFORMAZIONE_NESSUN_ENTE_PREV_MA_COD_ENTE_PREVIDENZIALE_VALORIZZATO = 12003;
  public static final long DATI_TRASFORMAZIONE_COD_AGEVOLAZIONE_ERRATO = 12004;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_ERRATO = 12005;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_APPRENDISTATO_NON_AMMESSO = 12006;
  public static final long DATI_TRASFORMAZIONE_LAVORATORE_COOBBLIGATO_NON_VALORIZZATO_PER_TIPO_CONTRATTO_RIPARTITO = 12007;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TIPO_COMUNICAZIONE = 12008;
  public static final long DATI_TRASFORMAZIONE_FLG_SOCIO_LAVORATORE_ERRATO_UNILAV = 12009;
  public static final long DATI_TRASFORMAZIONE_QUALIFICA_PROFESSIONALE_ISTAT_NON_VALIDO = 12010;
  public static final long DATI_TRASFORMAZIONE_ORE_SETTIMANALI_MEDIE_NON_VALORIZZATE = 12011;
  public static final long DATI_TRASFORMAZIONE_TIPO_ORARIO_ERRATO_UNILAV = 12012;
  public static final long DATI_TRASFORMAZIONE_TIPO_LAVORAZIONE_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 12013;
  public static final long DATI_TRASFORMAZIONE_NUM_GG_PREVISTI_AGR_NON_VALORIZZATO = 12014;
  public static final long DATI_TRASFORMAZIONE_CCNL_RETRIBUZIONE_E_LIVELLO_NON_VALORIZZATI = 12015;
  public static final long DATI_TRASFORMAZIONE_CCNL_NON_VALIDO = 12016;
  public static final long DATI_TRASFORMAZIONE_COD_COMUNE_SEDE_PREC_NON_VALIDO = 12017;
  public static final long DATI_TRASFORMAZIONE_INDIRIZZO_SEDE_PREC_NON_VALORIZZATO = 12018;
  public static final long DATI_TRASFORMAZIONE_COD_FISCALE_DATORE_LAVORO_DISTACCO_NON_VALORIZZATO = 12019;
  public static final long DATI_TRASFORMAZIONE_DENOMINAZIONE_DATORE_LAVORO_DISTACCO_NON_VALORIZZATO = 12020;
  public static final long DATI_TRASFORMAZIONE_ATECO_DATORE_LAVORO_DISTACCO_NON_VALORIZZATO = 12021;
  public static final long DATI_TRASFORMAZIONE_ATECO_DATORE_LAVORO_DISTACCO_NON_VALIDO = 12022;
  public static final long DATI_TRASFORMAZIONE_PATINAIL_NON_VALORIZZATO = 12023;
  public static final long DATI_TRASFORMAZIONE_COD_COMUNE_SEDE_LAV_DISTACCO_NON_VALIDO = 12024;
  public static final long DATI_TRASFORMAZIONE_CAP_SEDE_LAV_DISTACCO_NON_VALORIZZATO = 12025;
  public static final long DATI_TRASFORMAZIONE_INDIRIZZO_SEDE_LAV_DISTACCO_NON_VALORIZZATO = 12026;
  public static final long DATI_TRASFORMAZIONE_EMAIL_TELEFONO_E_FAX_SEDE_LAV_DISTACCO_NON_VALORIZZATI = 12027;
  public static final long DATI_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_NON_VALIDO = 12028;
  public static final long DATI_TRASFORMAZIONE_FORMA_NON_VALIDA_PER_CODICE_TRASFORMAZIONE = 12029;
  public static final long DATI_TRASFORMAZIONE_TIPO_ORARIO_NON_VALIDO_PER_CODICE_TRASFORMAZIONE = 12030;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_RIPARTITO_NON_ANCORA_GESTITO = 12031;
  public static final long DATI_TRASFORMAZIONE_CODICE_TRASFORMAZIONE_DL_DATA_FINE_RAPPORTO_NON_VALORIZZATA = 12032;
  public static final long DATI_TRASFORMAZIONE_DATA_FINE_RAPPORTO_INFERIORE_DATA_TRASFORMAZIONE = 12033;
  public static final long DATI_TRASFORMAZIONE_FORMA_RAPPORTO_INDETERMINATA_NON_VALIDA_PER_COD_TRASFORMAZIONE_NON_DL = 12034;
  public static final long DATI_TRASFORMAZIONE_DATA_FINE_RAPPORTO_INFERIORE_DATA_INIZIO_RAPPORTO = 12035;
  public static final long DATI_TRASFORMAZIONE_FINE_RAPPORTO_NON_VALORIZZATA_PER_FORMA_RAPPORTO_DETERMINATA = 12036;
  public static final long DATI_TRASFORMAZIONE_PATINAIL_FORMATO_LUNGHEZZA_MIN_MAX_NON_VALIDO = 12037;
  public static final long DATI_TRASFORMAZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA = 12038;
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_DI_TRASFORMAZIONE_NON_AMMESSA = 12039;
  public static final long DATI_TRASFORMAZIONE_CODICE_ENTE_PREVIDENZIALE_NON_VALORIZZATO = 12040;
  public static final long DATI_TRASFORMAZIONE_PAT_INAIL_ERRATO = 12041;
  public static final long DATI_TRASFORMAZIONE_LIVELLO_INQUADRAMENTO_NON_VALORIZZATO = 12042;
  public static final long DATI_TRASFORMAZIONE_NUM_GG_PREVISTI_AGR_VALORIZZATO_PER_CONTRATTO_NON_AGRICOLO = 12043;
  public static final long DATI_TRASFORMAZIONE_FLG_DISTACCO_PARZIALE_ERRATO = 12044;
  public static final long DATI_TRASFORMAZIONE_FLG_DISTACCO_AZIENDA_ESTERA = 12045;
  public static final long DATI_TRASFORMAZIONE_COD_FISCALE_DATORE_LAVORO_DISTACCO_NON_VALIDO = 12046;
  public static final long DATI_TRASFORMAZIONE_COD_COMUNE_SEDE_LAV_DISTACCO_NON_VALORIZZATO = 12047;
  public static final long DATI_TRASFORMAZIONE_SEDE_LEGALE_EMAIL_FORMATO_NON_CORRETTO = 12048;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM_DATA_INIZIO_MAGGIORE_01_01_2008 = 12049;
  public static final long DATI_TRASFORMAZIONE_TRASFERIMENTO_LAVORATORE_CON_FLAG_DISTACCO_VALORIZZATI = 12050;
  public static final long DATI_TRASFORMAZIONE_DATORE_DEL_DISTACCO_NON_VALORIZZATO = 12051;
  public static final long DATI_TRASFORMAZIONE_DATORE_DEL_DISTACCO_VALORIZZATO = 12052;
  public static final long DATI_TRASFORMAZIONE_DISTACCO_DEL_LAVORATORE_CON_DATI_TRASFERIMENTO_LAVORATORE_VALORIZZATI = 12053;
  public static final long DATI_TRASFORMAZIONE_TIPO_ORARIO_NON_AMMESSO_PER_TIPO_CONTRATTO = 12054;
  public static final long DATI_TRASFORMAZIONE_ORE_SETTIMANALI_MEDIE_VALORIZZATE = 12055;
  public static final long DATI_TRASFORMAZIONE_ENTE_PREV_VALORIZZATO_MA_COD_ENTE_PREVIDENZIALE_NON_VALORIZZATO = 12056;
  public final static long DATI_TRASFORMAZIONE_TEMPO_INDETERMINATO_CON_DATA_FINE_VALORIZZATA = 12057;
  public static final long DATI_TRASFORMAZIONE_COD_FISCALE_DATORE_LAVORO_DISTACCO_NON_AMMESSO = 12058;
  public static final long DATI_TRASFORMAZIONE_PATINAIL_NON_AMMESSO = 12059;
  public static final long DATI_TRASFORMAZIONE_CAP_SEDE_LAV_DISTACCO_NON_AMMESSO = 12060; 
  public static final long DATI_TRASFORMAZIONE_COD_STATO_ESTERO_SEDE_LAV_DISTACCO_NON_VALIDO = 12061;
  public static final long DATI_TRASFORMAZIONE_COD_STATO_ESTERO_SEDE_LAV_DISTACCO_NON_VALORIZZATO = 12062;
  public static final long DATI_TRASFORMAZIONE_DIFFERENZA_DATA_FINE_DATA_INIZIO_SUPERIORE_A_50_ANNI = 12063;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNILAV = 12064;
  public static final long DATI_TRASFORMAZIONE_TIPO_CONTRATTO_NON_AMMESSO_PER_TRACCIATO_UNISOM = 12065;
  public static final long DATI_TRASFORMAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_AMMESSO = 12066;
  public static final long DATI_TRASFORMAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALIDO = 12067;
  public static final long DATI_TRASFORMAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 12068;  
  public static final long DATI_TRASFORMAZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_AMMESSO = 12069;
  public static final long DATI_TRASFORMAZIONE_TEMPO_INDETERMINATO_CON_LAVORO_STAGIONALE = 12070;
  public static final long DATI_TRASFORMAZIONE_COD_AGEVOLAZIONE_DUPLICATO = 12071;
  //72160-Adeguamenti 2014
  public static final long DATI_TRASFORMAZIONE_CCNL_NON_VALORIZZATO = 12072;
  public static final long DATI_TRASFORMAZIONE_RETRIBUZIONE_NON_VALORIZZATA = 12073;
  //
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 12074;
  public static final long DATI_TRASFORMAZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_VALORIZZATO = 12075;
  public static final long DATI_TRASFORMAZIONE_CATEGORIA_TIROCINANTE_NON_VALORIZZATO = 12076;
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_TIROCINIO_NON_VALORIZZATO = 12077;
  //
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 12078;
  public static final long DATI_TRASFORMAZIONE_DENOMINAZIONE_ENTE_PROMOTORE_TIROCINIO_NON_AMMESSO = 12079;
  public static final long DATI_TRASFORMAZIONE_CATEGORIA_TIROCINANTE_NON_AMMESSA = 12080;
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_TIROCINIO_NON_AMMESSA = 12081;
  public static final long DATI_TRASFORMAZIONE_TIPOLOGIA_TIROCINIO_CATEGORIA_TIROCINANTE_ACCOPPIAMENTO_NON_VALIDO = 12082;
  public static final long DATI_TRASFORMAZIONE_FLAG_LAVORO_STAGIONALE_ERRATO = 12083;
  public static final long DATI_TRASFORMAZIONE_DATA_FINE_RAPPORTO_NON_VALORIZZATA_CON_FLAG_LAVORO_STAGIONALE_SI = 12084;
  //
  public static final long DATI_TRASFORMAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_6_MESI = 12085;
  public static final long DATI_TRASFORMAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_12_MESI = 12086;
  public static final long DATI_TRASFORMAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_24_MESI = 12087;
  //
  public static final long DATI_TRASFORMAZIONE_CODICE_FISCALE_SOGGETTO_PROMOTORE_UGUALE_CODICE_FISCALE_DATORE = 12088;  
  //
  public static final long DATI_TRASFORMAZIONE_CODICE_TIPOLOGIA_ENTE_PROMOTORE_TIROCINIO_NON_VALIDO = 12089;
  public static final long DATI_TRASFORMAZIONE_CODICE_CATEGORIA_TIROCINANTE_NON_VALIDO = 12090;
  public static final long DATI_TRASFORMAZIONE_CODICE_TIPOLOGIA_TIROCINIO_NON_VALIDO = 12091;
  public static final long DATI_TRASFORMAZIONE_DURATA_RAPPORTO_NON_CONSENTITA_MAGGIORE_3_MESI = 12092;
  public static final long DATI_TRASFORMAZIONE_DURATA_RAPPORTO_TIROCINIO_NON_CONSENTITA = 12093;//71862 - COMONL-1529
  public static final long DATI_TRASFORMAZIONE_AGEVOLAZIONI_NON_AMMESSE = 12102;
  public static final long DATI_TRASFORMAZIONE_LIVELLO_INQUADRAMENTO_NON_VALIDO_PER_CCNL = 12103;
  public static final long DATI_TRASFORMAZIONE_IMPOSSIBILE_CALCOLARE_RETRIBUZIONE_MANCANZA_CAMPI_OBBLIGATORI = 12104;
  public static final long DATI_TRASFORMAZIONE_RETRIBUZIONE_INSERITA_NON_VALIDA = 12105;
  public static final long DATI_TRASFORMAZIONE_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 12106;

  
  

  public static final long  DATI_CESSAZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 80070;
  public static final long  DATI_CESSAZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 80071;
  public static final long  DATI_CESSAZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 80072;
  public static final long  DATI_CESSAZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 80073;
  
  public static final long  DATI_PROROGA_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 11064;
  public static final long  DATI_PROROGA_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 11065;
  public static final long  DATI_PROROGA_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 11066;
  public static final long  DATI_PROROGA_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 11067;
  public static final long  DATI_PROROGA_AGEVOLAZIONI_NON_AMMESSE = 11071;
  public static final long  DATI_PROROGA_LIVELLO_INQUADRAMENTO_NON_VALIDO_PER_CCNL = 11072;
  public static final long  DATI_PROROGA_IMPOSSIBILE_CALCOLARE_RETRIBUZIONE_MANCANZA_CAMPI_OBBLIGATORI = 11073;
  public static final long  DATI_PROROGA_RETRIBUZIONE_INSERITA_NON_VALIDA = 11074;
  public static final long  DATI_PROROGA_CCNL_INCONGRUENTE_TIPO_CONTRATTO = 11075;
  
  public static final long  DATI_TRASFORMAZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATO = 12094;
  public static final long  DATI_TRASFORMAZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_VALORIZZATA = 12095;
  public static final long  DATI_TRASFORMAZIONE_CATEGORIA_LAVORATORE_ASSUNZIONE_OBBLIGATORIA_NON_AMMESSA = 12096;
  public static final long  DATI_TRASFORMAZIONE_FLAG_ASSUNZIONE_OBBLIGATORIA_CATEGORIA_LAVORATORE_INCONGRUENTI = 12097;
  public static final long  DATI_TRASFORMAZIONE_DATA_FINE_PERIODO_FORMATIVO_NON_VALORIZZATO = 12098;
		
  
  //URGENZA
  public static final long COMUNICAZIONE_DI_URGENZA_NON_AMMESSA = 13001;
  //UNIDOM
  public static final long COMUNICAZIONE_LAVORO_DOMESTICO_NON_AMMESSA = 13002;
  //TRACCIATO
  public static final long TIPO_TRACCIATO_NON_AMMESSO = 13003; 
  //DATORE LAVORO DOMESTICO
  public static final long DATI_LAVORO_DOMESTICO_FLG_INVALIDITA_E_O_FLG_CONVIVENZA_NON_VALORIZZATI = 14001;
 
//COMUNI
  public static final long RETRIBUZIONE_UGUALE_ZERO_NON_AMMESSA = 100;
  public static final long CCNL_NON_VALIDO_PER_CONTRATTO_SOLO_PUBBLICA_AMMINISTRAZIONE = 101;
}
