/*
* SPDX-FileCopyrightText: Copyright 2019 - 2022 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
import { Injectable, Type } from '@angular/core';
import { QUADRI_ASSUNZIONE_AND_SOMM, QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV, QUADRI_CESSAZIONE_MISSIONE, QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE, QUADRI_SOMM_E_MISSIONE, QUADRI_TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE, QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG, QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE, QUADRI_TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE, QUADRI_URG_SI, QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE, QUADRI_VARIAZIONE_DATORE, QUADRI_ASSUNZIONE_AND_SOMM_CON_TUTORE, QUADRI_SOMM_E_MISSIONE_CON_TUTORE, QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE_CON_TUTORE, QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE_CON_TUTORE, QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG_CON_TUTORE, QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV_CON_TUTORE, QUADRI_CESSAZIONE_MISSIONE_CON_TUTORE, QUADRI_TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE_CON_TUTORE, QUADRI_TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE_CON_TUTORE, QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE_CON_TUTORE, QUADRI_VARIAZIONE_DATORE_RAG_SOCIALE, QUADRI_VARIAZIONE_DATORE_TRASF } from '../components/quadri/constants-quadri';
import { AdQuadro } from '../models/ad-quadro';


export const TIPO_QUADRO_COM = {
    ASSUNZIONE: 'ASS',
    ASSUNZIONE_CON_TUTORE: 'ASS_TUTORE',
    CESSAZIONE: 'CES',
    CESSAZIONE_CON_TUTORE: 'CES_TUTORE',
    TRASFORMAZIONE: 'TRS',
    TRASFORMAZIONE_CON_TUTORE: 'TRS_TUTORE',
    PROROGA: 'PRO',
    PROROGA_CON_TUTORE: 'PRO_TUTORE',
    TRASFERIMENTO_DISTACCO: 'TRD',
    TRASFERIMENTO_DISTACCO_CON_TUTORE: 'TRD_TUTORE',
    URGENZA: 'URG', // NO TUTORE
    VARIAZIONE_DATORE: 'VAR',
    VARIAZIONE_DATORE_RAG_SOCIALE: 'VAR_RS',
    VARIAZIONE_DATORE_TRASF: 'VAR_T',
    VARIAZIONE_DATORE_CON_TUTORE: 'VAR_TUTORE',
    CESSAZIONE_DEL_RAPPORTO_DI_LAVORO: '9',
    CESSAZIONE_DEL_RAPPORTO_DI_LAVORO_CON_TUTORE: '9_TUTORE',
    TRASFERIMENTO_ALTRA_SEDE_OPERATIVA_AGENZIA: '7',
    TRASFERIMENTO_ALTRA_SEDE_OPERATIVA_AGENZIA_CON_TUTORE: '7_TUTORE',
    TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE: '6',
    TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE_CON_TUTORE: '6_TUTORE',
    TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE: '4',
    TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE_CON_TUTORE: '4_TUTORE',
    TRASFORMAZIONE_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE: '5',
    TRASFORMAZIONE_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE_CON_TUTORE: '5_TUTORE',
    PROROGA_DELLA_MISSIONE_IN_CASO_DI_RAPPORTO_A_TEMPO_INDETERMINATO: '3',
    PROROGA_DELLA_MISSIONE_IN_CASO_DI_RAPPORTO_A_TEMPO_INDETERMINATO_CON_TUTORE: '3_TUTORE',
    PROROGA_DEL_RAPPORTO_DI_LAVORO_E_DELLA_MISSIONE: '2PROEMISS',
    PROROGA_DEL_RAPPORTO_DI_LAVORO_E_DELLA_MISSIONE_CON_TUTORE: '2PROEMISS_TUTORE',
    PROROGA_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE: '1',
    PROROGA_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE_CON_TUTORE: '1_TUTORE',
    CESSAZIONE_MISSIONE: '8',
    CESSAZIONE_MISSIONE_CON_TUTORE: '8_TUTORE',
    SOMMINISTRAZIONE: '0',
    SOMMINISTRAZIONE_CON_TUTORE: '0_TUTORE',
    SOMMINISTRAZIONE_E_MISSIONE: '2SOMEMISS',
    SOMMINISTRAZIONE_E_MISSIONE_CON_TUTORE: '2SOMEMISS_TUTORE'
};
@Injectable()
export class LoaderService {

    constructor() {}

    private loAdQuadri(configurazioneQuadri: string): AdQuadro[] {
        switch (configurazioneQuadri) {
            case TIPO_QUADRO_COM.ASSUNZIONE: {
                return QUADRI_ASSUNZIONE_AND_SOMM;
            }
            case TIPO_QUADRO_COM.ASSUNZIONE_CON_TUTORE: {
                return QUADRI_ASSUNZIONE_AND_SOMM_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.CESSAZIONE: {
                return QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV;
            }
            case TIPO_QUADRO_COM.CESSAZIONE_CON_TUTORE: {
                return QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE: {
                return QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE_CON_TUTORE: {
                return QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.PROROGA: {
                return QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE;
            }
            case TIPO_QUADRO_COM.PROROGA_CON_TUTORE: {
                return QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_DISTACCO: {
                return QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_DISTACCO_CON_TUTORE: {
                return QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.URGENZA: {
                return QUADRI_URG_SI;
            }
            case TIPO_QUADRO_COM.VARIAZIONE_DATORE_RAG_SOCIALE: {
                return QUADRI_VARIAZIONE_DATORE_RAG_SOCIALE;
            }
            case TIPO_QUADRO_COM.VARIAZIONE_DATORE_TRASF: {
                return QUADRI_VARIAZIONE_DATORE_TRASF;
            }
            case TIPO_QUADRO_COM.VARIAZIONE_DATORE_CON_TUTORE: {
                return QUADRI_VARIAZIONE_DATORE;
            }
            case TIPO_QUADRO_COM.CESSAZIONE_DEL_RAPPORTO_DI_LAVORO: {
                return QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV;
            }
            case TIPO_QUADRO_COM.CESSAZIONE_DEL_RAPPORTO_DI_LAVORO_CON_TUTORE: {
                return QUADRI_CESSAZIONE_AND_CESSAZIONE_RAPP_LAV_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_ALTRA_SEDE_OPERATIVA_AGENZIA: {
                return QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_ALTRA_SEDE_OPERATIVA_AGENZIA_CON_TUTORE: {
                return QUADRI_TRASFERIMENTO_DISTACCO_AND_TRASF_ALTRA_SEDE_OP_AG_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE: {
                return QUADRI_TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE;
            }
            case TIPO_QUADRO_COM.TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE_CON_TUTORE: {
                return QUADRI_TRASFERIMENTO_ALTRA_SEDE_LAVORO_DITTA_UTILIZZATRICE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE: {
                return QUADRI_TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE_CON_TUTORE: {
                return QUADRI_TRASFORMAZIONE_IN_COSTANZA_DI_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE: {
                return QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE;
            }
            case TIPO_QUADRO_COM.TRASFORMAZIONE_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE_CON_TUTORE: {
                return QUADRI_TRASFORMAZIONE_AND_TRASFORMAZIONE_RAPPORTO_LAVORO_ASSENZA_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.PROROGA_DELLA_MISSIONE_IN_CASO_DI_RAPPORTO_A_TEMPO_INDETERMINATO: {
                return QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE;
            }
            case TIPO_QUADRO_COM.PROROGA_DELLA_MISSIONE_IN_CASO_DI_RAPPORTO_A_TEMPO_INDETERMINATO_CON_TUTORE: {
                return QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.PROROGA_DEL_RAPPORTO_DI_LAVORO_E_DELLA_MISSIONE: {
                return QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE;
            }
            case TIPO_QUADRO_COM.PROROGA_DEL_RAPPORTO_DI_LAVORO_E_DELLA_MISSIONE_CON_TUTORE: {
                return QUADRI_PROROGA_MISSIONE_RAPPORTO_INDETERMINATO_AND_LAVORO_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.PROROGA_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE: {
                return QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE;
            }
            case TIPO_QUADRO_COM.PROROGA_DEL_RAPPORTO_DI_LAVORO_IN_ASSENZA_DI_MISSIONE_CON_TUTORE: {
                return QUADRI_PROROGA_AND_PROROGA_LAVORO_ASSENZA_DI_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.CESSAZIONE_MISSIONE: {
                return QUADRI_CESSAZIONE_MISSIONE;
            }
            case TIPO_QUADRO_COM.CESSAZIONE_MISSIONE_CON_TUTORE: {
                return QUADRI_CESSAZIONE_MISSIONE_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.SOMMINISTRAZIONE: {
                return QUADRI_ASSUNZIONE_AND_SOMM;
            }
            case TIPO_QUADRO_COM.SOMMINISTRAZIONE_CON_TUTORE: {
                return QUADRI_ASSUNZIONE_AND_SOMM_CON_TUTORE;
            }
            case TIPO_QUADRO_COM.SOMMINISTRAZIONE_E_MISSIONE: {
                return QUADRI_SOMM_E_MISSIONE;
            }
            case TIPO_QUADRO_COM.SOMMINISTRAZIONE_E_MISSIONE_CON_TUTORE: {
                return QUADRI_SOMM_E_MISSIONE_CON_TUTORE;
            }
            default: {
               // statements;
               break;
            }
        }
    }

    public getQuadri(configurazioneQuadri: string): AdQuadro[] {
        return this.loAdQuadri(configurazioneQuadri);
    }

    public addTutore() {

    }

}
